.TH EMESENE "1" "October 11, 2007"
.SH NAME
emesene \- Instant Messaging Client.

.SH SYNOPSIS
.B emesene
.RI [\fIOPTIONS\fR]

.SH DESCRIPTION
\fBemesene\fP is a multiplatform istant messaging client for Live Messenger 
and Jabber networks (GTalk, Facebook Chat, etc.) written in python.
.SH OPTIONS
emesene options: (CURRENTLY IN DEVELOPMENT, SO THEY WON'T WORK)
.TP
.B \-m, \-\-minimized
Start emesene minimized.
.TP
.B \-i, \-\-iconified
Start emesene iconified.
.TP
.B \-\-user=\fImail@address\fR
Login as mail@address
.TP
.B \-\-safe
Don't use cache for the userlist.
.TP
.B \-\-leakdebug
Print leak debug messages.

.SH AUTHOR
This manual page was written by Emilio Pozuelo Monfort <pochu@ubuntu.com>.
