.TH EMESENE 1  "August 23, 2012"
.SH NAME
emesene \- an instant messaging client
.SH DESCRIPTION
.B emesene 2
tries to be a simple but feature complete program that allows one to chat
using MSN and Jabber/XMPP based networks.
.sp
From its roots emesene 2 provides a UI that is easy to use by users coming
from Windows Live Messenger but doing special focus on consistency and
simplicity.
.sp
Support for Jabber/XMPP based networks through the use of different backends is
provided but without removing features from the main protocol.
.sp
Since emesene 2 is a single protocol/account client you will have to start more
than one instance to use more than one account. If you think this is a problem
we recommend clients like Pidgin, Empathy or Kopete that are built to handle
multiple accounts.
