.TH EMESENE "1" "October 11, 2007"
.SH NAME
Emesene \- MSN Messenger Client.

.SH SYNOPSIS
.B emesene
.RI [\fIOPTIONS\fR]

.SH DESCRIPTION
\fBEmesene\fP is a multiplattform MSN messenger client written in Python 
and PyGTK.
.SH OPTIONS
Emesene options:
.TP
.B \-m, \-\-minimized
Start emesene minimized.
.TP
.B \-i, \-\-iconified
Start emesene iconified.
.TP
.B \-\-user=\fImail@address\fR
Login as mail@address
.TP
.B \-\-safe
Don't use cache for the userlist.
.TP
.B \-\-leakdebug
Print leak debug messages.

.SH AUTHOR
This manual page was written by Emilio Pozuelo Monfort <pochu@ubuntu.com>.
